### ISSUE TITLE
Aggregation logic

### ISSUE THREAD

**Issue by kollol-chowdhury-incontact** [Moesif/kong-plugin-moesif#75]
Is the data aggregated per worker?
What happens if the worker crashes or the instance where Kong is running dies before the aggregation count reached the threshold value? We will be losing the data in this case.

Please need help around this question

**Comment by dgilling** [comment]
@kollol-chowdhury-incontact Data is batched per worker. You can control when this is sent via the config 

[config.event_queue_size](https://www.moesif.com/docs/server-integration/kong-api-gateway/#parameters).

It would be rare you see a large amount of data loss as the plugin constantly streams this data to Moesif. We do have logs that can be printed to better track this.

**Comment by kollol-chowdhury-incontact** [comment]
Hi Derek,
Thanks for replying back.
So even if it not huge data loss, there can be a little data loss right because of the scenarios i mentioned?

**Comment by dgilling** [comment]
@kollol-chowdhury-incontact Does your worker restart multiple times a month? This would point to a larger issue around capacity planning or instability since this is expected to a rare event. If you're API is very low volume, you could reduce [config.event_queue_size](https://www.moesif.com/docs/server-integration/kong-api-gateway/#parameters) to a small number like 1 or 10 events. However, we **strongly(( don't recommend a low value for event_queue_size for a high volume API as you will run into performance and network issues.

The way we look at this issue is as follows: 
Let's say your API receives 1 Billion API Calls a month, and you have 2 worker restarts during the month and [config.event_queue_size](https://www.moesif.com/docs/server-integration/kong-api-gateway/#parameters) is set to 1000 events.
In this case, then the max events lost for the month would total 2,000. This would be 2,000 out of 1,000,000,000 events or a data loss of `0.0002%`. Usually, this is a manageable amount. However, happy to jump on a call to better understand your. specific application and concerns here. Feel free to set up a call here: https://meetings.hubspot.com/derricg/30min

**Comment by dgilling** [comment]
@kollol-chowdhury-incontact is there still an issue here? Closing ticket.
